version: "2.2"
services:
  node:
    build: ./.docker/node/build
    working_dir: /srv
    stdin_open: true
    env_file:
      - .env
    environment:
      PATH: /srv/node_modules/.bin:$PATH
    volumes:
      - ./:/srv
      - ./.docker/node/.cache:/home/node/.cache
      - ./.docker/node/.config:/home/node/.config
  hardhat:
    build: ./.docker/node/build
    working_dir: /srv
    stdin_open: true
    command: ["lerna", "run", "--stream", "--scope", "@librt/node", "start"]
    env_file:
      - .env
    environment:
      PATH: /srv/node_modules/.bin:$PATH
    ports:
      - "8545:8545"
    volumes:
      - ./:/srv
      - ./.docker/node/.cache:/home/node/.cache
      - ./.docker/node/.config:/home/node/.config
  relay:
    image: "walletconnect/relay-server:v2.0-dev"
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis/data:/var/lib/redis
