version: "2.2"
services:
  node:
    build: ./.docker/node/build
    working_dir: /srv
    env_file:
      - .env
    environment:
      PATH: /srv/node_modules/.bin:$PATH
    volumes:
      - ./:/srv
      - ./.docker/node/.cache:/home/node/.cache
      - ./.docker/node/.config:/home/node/.config
  hardhat:
    build: ./.docker/node/build
    working_dir: /srv
    command: ["lerna", "run", "--stream", "node"]
    env_file:
      - .env
    environment:
      PATH: /srv/node_modules/.bin:$PATH
    ports:
      - "8545:8545"
    volumes:
      - ./:/srv
      - ./.docker/node/.cache:/home/node/.cache
      - ./.docker/node/.config:/home/node/.config
